// apps/writing-react-tr/src/routes/root.tsx
import { Scripts, useHead } from '@marbemac/ssr-react';
import { Box, PrimitivesProvider } from '@marbemac/ui-primitives-react';
import type { Twind } from '@marbemac/ui-twind';
import { createStylePropsResolver } from '@marbemac/ui-twind';
import type { QueryClient } from '@tanstack/react-query';
import { Outlet, RouterContext, useRouter } from '@tanstack/router';
import React from 'react';

import { SiteNav } from '~/components/SiteNav.tsx';
import { Providers } from '~/providers.tsx';
import { RouterHydrationContext } from '~/utils/router-hydration-context.ts';
import type { createTRPCClient } from '~/utils/trpc.ts';

export const routerContext = new RouterContext<{
  queryClient: QueryClient;
  trpc: ReturnType<typeof createTRPCClient>;
  twind: Twind;
}>();

export const rootRoute = routerContext.createRootRoute({
  component: Root,
  wrapInSuspense: false,
});

function Root() {
  console.log('Root.render');

  const router = useRouter();
  const { queryClient, trpc, twind } = router.options.context;

  useHead({ title: 'Writing Demo App' });

  return (
    <PrimitivesProvider as="html" stylePropResolver={createStylePropsResolver(twind)} tw="min-h-screen">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link
          rel="preload"
          href="/assets/fonts/inter/latin-variable.woff2"
          as="font"
          crossOrigin="anonymous"
          type="font/woff2"
        />
      </head>

      <Box as="body" tw="min-h-screen">
        <Providers queryClient={queryClient} trpc={trpc}>
          <Box tw="w-28 border-r p-4">
            <SiteNav />
          </Box>

          <Outlet />
        </Providers>

        <DehydrateRouter />

        <Scripts />
      </Box>
    </PrimitivesProvider>
  );
}

export function DehydrateRouter() {
  const dehydrated = React.useContext(RouterHydrationContext);

  return (
    <script
      suppressHydrationWarning
      dangerouslySetInnerHTML={{
        __html: `
          window.__TSR_DEHYDRATED__ = ${JSON.stringify(dehydrated)}
        `,
      }}
    />
  );
}

// apps/writing/src/root.tsx
import './root.css';

import { Box, Themed } from '@marbemac/ui-primitives';
import { Body, Head, Html, Scripts, useRequest } from '@marbemac/ui-solid-js';
import { Link as MetaLink, Meta, Title } from '@solidjs/meta';
import { useRoutes } from '@solidjs/router';
import { QueryClientProvider } from '@tanstack/solid-query';
import { Suspense } from 'solid-js';
import { HydrationScript, NoHydration } from 'solid-js/web';

import { QueryDevtools } from '~/components/QueryDevtools/index.js';
import { createRoutes } from '~/routes.js';
import { createQueryClient } from '~/utils/query-client.js';

const routeManifest = import.meta.env.DEV ? [] : '$ROUTE_MANIFEST';

export function App() {
  // const manifest = useContext(manifestContext);

  // console.log({ routeManifest, manifest });

  /**
   * Create a new query client on every request - cannot share cache on server.
   */
  const queryClient = createQueryClient();
  const Routes = useRoutes(createRoutes(queryClient));

  return (
    <Themed as={Html} lang="en" tw="min-h-screen">
      <Head>
        <Title>PLG</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />

        <MetaLink
          rel="preload"
          href="/fonts/inter/latin-variable.woff2"
          as="font"
          crossOrigin="anonymous"
          type="font/woff2"
        />
      </Head>

      <Box as={Body} tw="min-h-screen">
        <QueryClientProvider client={queryClient}>
          <Suspense fallback={'loading'}>
            <Routes />
          </Suspense>

          {/* Must wrap in div, or end up with blank screen (solid hydration issue?) */}
          <div>
            <QueryDevtools initialIsOpen={false} />
          </div>
        </QueryClientProvider>

        <Scripts />
      </Box>
    </Themed>
  );
}

function Scripts2() {
  const { env } = useRequest();

  return (
    <NoHydration>
      <HydrationScript />

      {import.meta.env.DEV ? (
        <>
          <script type="module" src="/@vite/client" $ServerOnly></script>
          <script type="module" src="/src/entry-client.tsx" $ServerOnly></script>
        </>
      ) : (
        <>
          <script type="module" src={`/${env.manifest!['entry-client']}`} $ServerOnly></script>
        </>
      )}
    </NoHydration>
  );
}
