// apps/writing-tr/src/routes/debug.tsx
import { Route } from '@tanstack/router';
import { Suspense } from 'react';

import { useTrpc } from '~/utils/trpc.ts';

import { rootRoute } from './root.tsx';

export const debugRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'debug',
  component: () => {
    return (
      <div className="p-2">
        <h1>Debug</h1>
        <Suspense fallback={<div>{`outer waiting...`}</div>}>
          <WaiterInner wait={2000} deferStream />

          <Waiter wait={2500} />
          <Waiter wait={4000} />
        </Suspense>
      </div>
    );
  },
});

const Waiter = (props: { wait: number }) => {
  return (
    <Suspense fallback={<div>{`waiting ${props.wait}...`}</div>}>
      <WaiterInner {...props} />
    </Suspense>
  );
};

const WaiterInner = ({ wait, deferStream }: { wait: number; deferStream?: boolean }) => {
  const query = useTrpc().posts.nested.wait.useQuery({ wait }, { meta: { deferStream } });

  return <div>result: {query.data}</div>;
};

// apps/writing-solid/src/routes/debug.tsx
import { Suspense } from 'solid-js';

import { Link } from '~/components/Link.tsx';
import { useTrpc } from '~/utils/trpc.ts';

export default function Debug() {
  return (
    <div>
      <h1>DEBUG</h1>
      <Link href="/">Go home</Link>
      <Inner wait={1000} />
      <Inner wait={2000} />
      <Inner wait={3000} />
      <Inner wait={4000} />
      <Inner wait={5000} />
      <Inner wait={6000} />
      <Inner wait={7000} />
    </div>
  );
}

const Inner = (props: { wait: number }) => {
  const query = useTrpc().posts.nested.wait.useQuery(() => ({ wait: props.wait }));

  return (
    <Suspense fallback={<div>{`waiting ${props.wait}...`}</div>}>
      <div>result {query.data}</div>
    </Suspense>
  );
};
