// apps/writing-react-tr/src/routes/debug.tsx
import { useHead } from '@marbemac/ssr-react';
import { Box } from '@marbemac/ui-primitives-react';
import type { TwProp } from '@marbemac/ui-styles';
import { Route } from '@tanstack/router';
import { Suspense } from 'react';

import { useTrpc } from '~/utils/trpc.ts';

import { rootRoute } from './root.tsx';

export const debugRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'debug',
  component: function DebugRoute() {
    useHead({ title: 'Debug page' });

    return (
      <div className="p-2">
        <Box as="h1" tw="text-warning-solid">
          Debug
        </Box>

        <Suspense fallback={<div>{`outer waiting...`}</div>}>
          <WaiterInner wait={2000} deferStream tw="text-2xl" />

          <Waiter wait={10000} tw="text-xl" />
          <Waiter wait={20000} tw="text-sm" />
        </Suspense>
      </div>
    );
  },
});

const Waiter = (props: { wait: number; tw?: TwProp }) => {
  return (
    <Suspense fallback={<div>{`waiting ${props.wait}...`}</div>}>
      <WaiterInner {...props} />
    </Suspense>
  );
};

const WaiterInner = ({ wait, deferStream, tw }: { wait: number; deferStream?: boolean; tw?: TwProp }) => {
  const query = useTrpc().posts.nested.wait.useQuery({ wait }, { meta: { deferStream } });

  return <Box tw={tw}>result: {query.data}</Box>;
};

// apps/writing-solid/src/routes/debug.tsx
import { Suspense } from 'solid-js';

import { Link } from '~/components/Link.tsx';
import { useTrpc } from '~/utils/trpc.ts';

export default function Debug() {
  return (
    <div>
      <h1>DEBUG</h1>
      <Link href="/">Go home</Link>
      <Inner wait={1000} />
      <Inner wait={2000} />
      <Inner wait={3000} />
      <Inner wait={4000} />
      <Inner wait={5000} />
      <Inner wait={6000} />
      <Inner wait={7000} />
    </div>
  );
}

const Inner = (props: { wait: number }) => {
  const query = useTrpc().posts.nested.wait.useQuery(() => ({ wait: props.wait }));

  return (
    <Suspense fallback={<div>{`waiting ${props.wait}...`}</div>}>
      <div>result {query.data}</div>
    </Suspense>
  );
};
