// apps/writing/src/root.tsx
import { TRPC_ROOT_PATH } from '@libs/internal-api/consts';
import { Box, Themed } from '@marbemac/ui-primitives';
import { Body, Head, Html, Scripts, useRequest } from '@marbemac/ui-solid-js';
import { Link as MetaLink, Meta, Title } from '@solidjs/meta';
import { useRoutes } from '@solidjs/router';
import { QueryClientProvider } from '@tanstack/solid-query';

// import { QueryDevtools } from '~/components/QueryDevtools/index.js';
import { createRoutes } from '~/routes.tsx';
import { createQueryClient } from '~/utils/query-client.js';
import { createTRPCClient, TrpcContext } from '~/utils/trpc.ts';

import type { AppPageEvent } from './server/types.ts';

export function App() {
  const request = useRequest<AppPageEvent>();

  /**
   * Create a new query client on every request - cannot share cache on server.
   */
  const queryClient = createQueryClient();
  const trpc = createTRPCClient({
    queryClient,
    trpcCaller: request.trpcCaller,
    httpBatchLinkOpts: {
      url: TRPC_ROOT_PATH,
    },
  });

  const Routes = useRoutes(createRoutes(trpc));

  return (
    <Themed as={Html} lang="en" tw="min-h-screen">
      <Head>
        <Title>PLG</Title>

        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <MetaLink rel="icon" href="/favicon.ico" />

        <MetaLink
          rel="preload"
          href="/assets/fonts/inter/latin-variable.woff2"
          as="font"
          crossOrigin="anonymous"
          type="font/woff2"
        />
      </Head>

      <Box as={Body} tw="min-h-screen">
        <QueryClientProvider client={queryClient}>
          <TrpcContext.Provider value={{ trpc }}>
            <Routes />

            {/* <QueryDevtools initialIsOpen={false} /> */}
          </TrpcContext.Provider>
        </QueryClientProvider>

        <Scripts />
      </Box>
    </Themed>
  );
}

// apps/writing/src/app/root.tsx
import './root.css';

import { useRoutes } from '@solidjs/router';
import { QueryClientProvider } from '@tanstack/solid-query';
import { Suspense, useContext } from 'solid-js';
import { HydrationScript, NoHydration } from 'solid-js/web';

import { QueryDevtools } from '~/components/QueryDevtools/index.js';
import { createQueryClient } from '~/utils/query-client.js';

import { manifestContext } from './manifest.js';
import { createRoutes } from './routes.js';

export function App() {
  /**
   * Create a new query client on every request - cannot share cache on server.
   */
  const queryClient = createQueryClient();
  const Routes = useRoutes(createRoutes(queryClient));

  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <Suspense fallback={'loading'}>
            <Routes />
          </Suspense>

          {/* Must wrap in div, or end up with blank screen (solid hydration issue?) */}
          <div>
            <QueryDevtools initialIsOpen={false} />
          </div>
        </QueryClientProvider>

        <Scripts />
      </body>
    </html>
  );
}

function Scripts() {
  const manifest = useContext(manifestContext);

  return (
    <NoHydration>
      <HydrationScript />

      {import.meta.env.DEV ? (
        <>
          <script type="module" src="/@vite/client" $ServerOnly></script>
          <script type="module" src="/src/app/entry-client.tsx" $ServerOnly></script>
        </>
      ) : (
        <>
          <script type="module" src={manifest['entry-client']} $ServerOnly></script>
        </>
      )}
    </NoHydration>
  );
}
