// packages/client/react/src/universal/server-context.tsx
import type { PageEvent } from '@marbemac/server-ssr';
import { createContext, useContext } from 'react';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ServerContext = createContext<PageEvent>({} as any);

export const useRequest = <T extends PageEvent = PageEvent>() => {
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  return useContext(ServerContext)! as Readonly<T>;
};

// packages/ui/ssr-solid/src/universal/server-context.tsx
import { createContext, useContext } from 'solid-js';

import type { PageEvent } from './types.ts';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ServerContext = createContext<PageEvent>({} as any);

export const useRequest = <T extends PageEvent = PageEvent>() => {
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  return useContext(ServerContext)! as Readonly<T>;
};
