// apps/writing-react-tr/src/server/render-to-stream.ts
import type { RenderToStreamFn } from '@marbemac/server-ssr';
import { TwindStream } from '@marbemac/server-twind-stream';
import { createQueryDataInjector } from '@marbemac/ssr-react/server';
import { uneval } from 'devalue';
import { renderToReadableStream } from 'react-dom/server';

import type { AppPageEvent, ServerEntry } from './types.ts';

export const renderToStream: RenderToStreamFn<AppPageEvent, ServerEntry> = async ({ render, pageEvent, tw }) => {
  const { app, queryClient, trackedQueries, blockingQueries } = await render({ pageEvent });

  const appStream = await renderToReadableStream(app);

  const isCrawler = false;
  if (isCrawler) {
    await appStream.allReady;
  }

  return appStream
    .pipeThrough(new TwindStream(tw))
    .pipeThrough(
      createQueryDataInjector({ pageEvent, blockingQueries, trackedQueries, queryClient, serialize: uneval }),
    );
};

// apps/writing-solid/src/server/render-to-stream.ts
import type { RenderToStreamFn } from '@marbemac/server-ssr';
import { TwindStream } from '@marbemac/server-twind-stream';
import { renderToStream as renderSolidStream } from 'solid-js/web';

import type { AppPageEvent, ServerEntry } from './types.ts';

export const renderToStream: RenderToStreamFn<AppPageEvent, ServerEntry> = async ({ render, pageEvent }) => {
  const { readable, writable } = new TwindStream(pageEvent.twind.tw);

  const appStream = renderSolidStream(() => render({ pageEvent }));

  appStream.pipeTo(writable);

  return readable;
};
