// packages/ui/primitives-solid/src/components/Button/button.tsx
import { Button as KButton } from '@kobalte/core';
import type { ButtonProps as BButtonProps, ButtonSlots } from '@marbemac/ui-styles';
import { buttonStyle, makeStaticClass } from '@marbemac/ui-styles';
import type { Component } from 'solid-js';
import { Show } from 'solid-js';
import { createMemo, splitProps } from 'solid-js';

import { createPolymorphicComponent } from '../../utils/polymorphic.ts';
import { Box } from '../Box/index.ts';
import type { IconProps } from '../Icon/index.ts';
import { Icon } from '../Icon/index.ts';
import { mergeThemeProps, useThemeClasses } from '../Themed/utils.ts';

const staticClass = makeStaticClass<ButtonSlots>('button');

export type ButtonProps = BButtonProps<Component<any>>;

const DEFAULT_SPINNER: IconProps['icon'] = 'spinner';

export const Button = createPolymorphicComponent<'button', ButtonProps>(props => {
  props = mergeThemeProps(
    'Button',
    {
      ...buttonStyle.defaultVariants,
    },
    props,
  );

  const themeClasses = useThemeClasses<ButtonSlots>('Button', props);

  const [local, styleProps, others] = splitProps(
    props,
    [
      'children',
      'UNSAFE_class',
      'slotClasses',
      'startIcon',
      'endIcon',
      'loadingIcon',
      'loadingText',
      'loadingPlacement',
    ],
    buttonStyle.variantKeys,
  );

  const styles = createMemo(() =>
    buttonStyle({ ...styleProps, isInteractive: !styleProps.isDisabled && !styleProps.isLoading }),
  );

  const startIcon = () => {
    if (!styleProps.isLoading) return local.startIcon;
    if (local.loadingText && local.loadingPlacement === 'end') return undefined;
    return DEFAULT_SPINNER;
  };

  const endIcon = () => {
    if (!styleProps.isLoading) return local.endIcon;
    if (local.loadingText && local.loadingPlacement === 'end') return DEFAULT_SPINNER;
    return undefined;
  };

  const content = () => {
    if (!styleProps.isLoading) return local.children;
    return local.loadingText;
  };

  const isIconButton = () => !content();

  return (
    <Box
      as={KButton.Root}
      UNSAFE_class={[
        styles().base({
          class: [staticClass('root'), themeClasses.root, local.slotClasses?.root],
        }),
        local.UNSAFE_class,
      ]}
      disabled={styleProps.isDisabled}
      {...others}
    >
      <Show when={startIcon() && (!isIconButton() || !endIcon())}>
        <Icon
          UNSAFE_class={styles().icon({
            class: [staticClass('icon'), themeClasses.icon, local.slotClasses?.icon],
          })}
          icon={startIcon()!}
          spin={styleProps.isLoading}
        />
      </Show>

      <Show when={content()}>
        <Box
          UNSAFE_class={styles().text({
            class: [staticClass('text'), themeClasses.text, local.slotClasses?.text],
          })}
        >
          {content()}
        </Box>
      </Show>

      <Show when={endIcon()}>
        <Icon
          UNSAFE_class={styles().icon({
            class: [staticClass('icon'), themeClasses.icon, local.slotClasses?.icon],
          })}
          icon={endIcon()!}
          spin={styleProps.isLoading}
        />
      </Show>
    </Box>
  );
});

// packages/ui/primitives/src/components/Button/button.tsx
import * as AK from '@ariakit/react';
import {
  type ButtonSlotProps,
  buttonStaticClass,
  buttonStyle,
  type ButtonStyleProps,
  splitPropsVariants,
} from '@marbemac/ui-styles';
import { forwardRef, useMemo } from 'react';

import { type ContextValue, createContext, useContextProps } from '../../utils/context.tsx';
import { Icon, type IconProps } from '../Icon/icon.tsx';

export interface ButtonProps extends AK.ButtonProps, ButtonStyleProps, ButtonSlotProps {
  /** If added, the button will show an icon before the button's label. */
  startIcon?: IconProps['icon'];

  /** If added, the button will show an icon after the button's label. */
  endIcon?: IconProps['icon'];

  /** The icon to show when `isLoading` is true. */
  loadingIcon?: IconProps['icon'];

  /** The label to show in the button when `isLoading` is true. */
  loadingText?: string;

  /** The placement of the loader when `isLoading` is true. */
  loadingPlacement?: 'start' | 'end';
}

export const [ButtonContext, useButtonContext] = createContext<ContextValue<ButtonProps, HTMLButtonElement>>({
  name: 'ButtonContext',
  strict: false,
});

const DEFAULT_SPINNER: IconProps['icon'] = 'spinner';

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(originalProps, ref) {
  [originalProps, ref] = useContextProps(originalProps, ref, ButtonContext);

  const [
    { className, classNames, children, startIcon, endIcon, loadingIcon, loadingText, loadingPlacement, ...props },
    variantProps,
  ] = splitPropsVariants(originalProps, buttonStyle.variantKeys);

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const slots = useMemo(() => buttonStyle(variantProps), Object.values(variantProps));
  const baseTw = slots.base({ class: [buttonStaticClass('base'), className] });
  const startIconTw = slots.startIcon({ class: [buttonStaticClass('startIcon'), classNames?.startIcon] });
  const endIconTw = slots.endIcon({ class: [buttonStaticClass('endIcon'), classNames?.endIcon] });
  const textTw = slots.text({ class: [buttonStaticClass('text'), classNames?.text] });

  const startIconElem = !variantProps.isLoading
    ? startIcon
    : loadingText && loadingPlacement === 'end'
      ? null
      : DEFAULT_SPINNER;

  const endIconElem = !variantProps.isLoading
    ? endIcon
    : loadingText && loadingPlacement === 'end'
      ? DEFAULT_SPINNER
      : null;

  const contentElem = !variantProps.isLoading ? children : loadingText;
  const hasContent = contentElem !== undefined && contentElem !== null;
  const isIconButton = !hasContent;

  return (
    <AK.Button {...props} ref={ref} className={baseTw} disabled={variantProps.disabled}>
      {startIconElem && (!isIconButton || !endIconElem) ? (
        <Icon fw className={startIconTw} icon={startIconElem} spin={variantProps.isLoading} />
      ) : null}

      {hasContent ? <div className={textTw}>{contentElem}</div> : null}

      {endIconElem ? <Icon className={endIconTw} icon={endIconElem} spin={variantProps.isLoading} fw /> : null}
    </AK.Button>
  );
});
