// packages/client/trpc-react/src/provider.ts
import type { AnyRouter } from '@marbemac/client-trpc';
import { createContext, useContext } from 'react';

import type { CreateTRPCReact } from './createTRPCReact.ts';

export const createTRPCProvider = <TRouter extends AnyRouter>() => {
  const TrpcContext = createContext<{ trpc?: CreateTRPCReact<TRouter> }>({});

  function useTrpc() {
    const context = useContext(TrpcContext);

    if (context === undefined) {
      throw new Error('`useTrpc` must be used within a `TrpcProvider`');
    }

    return context.trpc!;
  }

  return { TrpcContext, useTrpc };
};

// packages/client/trpc-solid/src/solid-client/provider.ts
import type { AnyRouter } from '@marbemac/client-trpc';
import { createContext, useContext } from 'solid-js';
import { CreateTRPCSolid } from './createTRPCSolid.ts';

export const createTRPCProvider = <TRouter extends AnyRouter>() => {
  const TrpcContext = createContext<{ trpc: CreateTRPCSolid<TRouter> }>();

  function useTrpc() {
    const context = useContext(TrpcContext);

    if (context === undefined) {
      throw new Error('`useTrpc` must be used within a `TrpcProvider`');
    }

    return context.trpc;
  }

  return { TrpcContext, useTrpc };
};
